# Generated by Django 5.0.3 on 2024-06-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
