# Generated by Django 5.0.3 on 2024-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_events_is_active_tabs_friendrequest_friendship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
